/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Component concreteComponent1 = new ConcreteDecoratorFuncion1(new ConcreteComponent1());
        concreteComponent1.doFunction1();
        concreteComponent1.doFunction2();
        concreteComponent1.doFunction3();
    }
}
